import vine from '@vinejs/vine'

export const siteSettingValidator = vine.compile(
  vine.object({
    siteName: vine.string().trim().minLength(3).maxLength(180),
    siteSubtitle: vine.string().trim().maxLength(180).optional(),
    address: vine.string().trim().maxLength(255).optional(),
    city: vine.string().trim().maxLength(120).optional(),
    state: vine.string().trim().maxLength(2).optional(),
    postalCode: vine.string().trim().maxLength(12).optional(),
    phone: vine.string().trim().maxLength(40).optional(),
    whatsapp: vine.string().trim().maxLength(40).optional(),
    email: vine.string().trim().email().maxLength(180).optional(),
    instagramUrl: vine.string().trim().url().maxLength(500).optional(),
    facebookUrl: vine.string().trim().url().maxLength(500).optional(),
    youtubeUrl: vine.string().trim().url().maxLength(500).optional(),
    mapsUrl: vine.string().trim().url().maxLength(1000).optional(),
    openingHours: vine.string().optional(),
    footerText: vine.string().optional(),
    homeEyebrow: vine.string().trim().maxLength(120).optional(),
    homeTitle: vine.string().trim().maxLength(180).optional(),
    homeSummary: vine.string().trim().maxLength(255).optional(),
    missionTitle: vine.string().trim().maxLength(120).optional(),
    missionText: vine.string().optional(),
    missionVisible: vine.boolean().optional(),
    valuesTitle: vine.string().trim().maxLength(120).optional(),
    valuesText: vine.string().optional(),
    valuesVisible: vine.boolean().optional(),
    trajectoryTitle: vine.string().trim().maxLength(120).optional(),
    trajectoryText: vine.string().optional(),
    trajectoryVisible: vine.boolean().optional(),
    trajectoryButtonText: vine.string().trim().maxLength(120).optional(),
    trajectoryButtonUrl: vine.string().trim().maxLength(500).optional(),
    contributionVisible: vine.boolean().optional(),
    contributionTitle: vine.string().trim().maxLength(120).optional(),
    contributionText: vine.string().trim().maxLength(800).optional(),
    pixKey: vine.string().trim().maxLength(255).optional(),
    pixBeneficiary: vine.string().trim().maxLength(180).optional(),
  })
)
